#!/usr/bin/env bash

# TODO add arg te specify wdl

if [ -z "$FDT_CURRENT_ALG_ROOT" ] ; then
    echo "FDT_CURRENT_ALG_ROOT must be set, please source setalgdir"
else

    cd $FDT_CURRENT_ALG_ROOT

    make validatewdl

    cd - #return to previous cwd
fi
